# Based on https://github.com/khulnasoft/ml-buildkit/blob/v0.6.14/workflows/build-pipeline.yml
name: build-pipeline

on:
  workflow_dispatch:
    inputs:
      build_args:
        description: "Arguments passed to build script"
        required: false
        default: ""
      working_directory:
        description: "Working directory from where the build command is run"
        required: false
        default: ""
      python_version:
        description: "Python version to use"
        required: false
        default: ""
  push:
  pull_request:

concurrency:
  group: build-pipeline-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment variables
        id: prepare
        shell: bash
        run: |
          set -euo pipefail
          # Prefer workflow_dispatch inputs, fall back to repository secrets, otherwise empty string.
          echo "BUILD_ARGS=${{ github.event.inputs.build_args || secrets.BUILD_ARGS || '' }}" >> "$GITHUB_ENV"
          echo "WORKING_DIRECTORY=${{ github.event.inputs.working_directory || secrets.WORKING_DIRECTORY || '' }}" >> "$GITHUB_ENV"
          echo "PYTHON_VERSION=${{ github.event.inputs.python_version || secrets.PYTHON_VERSION || '' }}" >> "$GITHUB_ENV"

          # Set host IP for use inside container actions. Use robust method with fallback.
          HOST_IP=$(ip route get 1 2>/dev/null | awk '{print $7; exit}' || hostname -I 2>/dev/null | awk '{print $1}')
          echo "_HOST_IP=${HOST_IP:-127.0.0.1}" >> "$GITHUB_ENV"

      - name: Run build scripts
        uses: ./.github/actions/build-environment
        with:
          build_args: ${{ env.BUILD_ARGS }}
          working_directory: ${{ env.WORKING_DIRECTORY }}
          python_version: ${{ env.PYTHON_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
